import type { Block } from "./api";

export const DEMO_BLOCKS: Block[] = [
  {
    block_id: "QRY-AMR-2026-0847",
    quarry_id: "APQRY-0023",
    length_m: 2.34,
    width_m: 1.12,
    height_m: 0.87,
    volume_m3: 2.28,
    confidence: 0.94,
    classification: "below_gangsaw",
    seigniorage_fee_inr: 4560,
    source: "robot",
    status: "approved",
    measurement_method: "robot_stereo_pointcloud",
  },
  {
    block_id: "QRY-AMR-2026-0848",
    quarry_id: "APQRY-0023",
    length_m: 3.1,
    width_m: 1.55,
    height_m: 1.3,
    volume_m3: 6.25,
    confidence: 0.88,
    classification: "above_gangsaw",
    seigniorage_fee_inr: 12500,
    source: "robot",
    status: "pending",
    measurement_method: "robot_stereo_pointcloud",
  },
  {
    block_id: "QRY-ONG-2026-0112",
    quarry_id: "APQRY-0041",
    length_m: 1.9,
    width_m: 0.95,
    height_m: 0.7,
    volume_m3: 1.26,
    confidence: 0.72,
    classification: "below_gangsaw",
    seigniorage_fee_inr: 2520,
    source: "mobile",
    status: "flagged",
    measurement_method: "mobile_monocular",
  },
];
